services:
  ############################################################################
  backend:
    build:
      context: ./containers/backend
      target: development
      dockerfile: Containerfile
    depends_on:
      - mail
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - ./containers/backend/server:/app
  ############################################################################
  database:
    build:
      context: ./containers/database
      dockerfile: Containerfile
    ports:
      - 5432:5432
  ############################################################################
  proxy:
    build:
      context: ./containers/proxy
      target: development
      dockerfile: Containerfile
    volumes:
      - ./containers/proxy/files/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - mail
  ############################################################################
  mail:
    image: axllent/mailpit:v1.27
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - mail
  ##############################################################################
  database-infisical:
    build:
      context: ./containers/database
      dockerfile: Containerfile
  ##############################################################################
  backend-infisical:
    networks:
      - mail
  ##############################################################################
  frontend:
    build:
      context: ./containers/frontend
      dockerfile: Containerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./containers/frontend/app:/app
networks:
  mail:
