/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoauthRouteRouteImport } from './routes/_noauth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as NoauthLoginRouteImport } from './routes/_noauth/login'
import { Route as NoauthForgotPasswordRouteImport } from './routes/_noauth/forgot-password'

const NoauthRouteRoute = NoauthRouteRouteImport.update({
  id: '/_noauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const NoauthLoginRoute = NoauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => NoauthRouteRoute,
} as any)
const NoauthForgotPasswordRoute = NoauthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => NoauthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof NoauthForgotPasswordRoute
  '/login': typeof NoauthLoginRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof NoauthForgotPasswordRoute
  '/login': typeof NoauthLoginRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_noauth': typeof NoauthRouteRouteWithChildren
  '/_noauth/forgot-password': typeof NoauthForgotPasswordRoute
  '/_noauth/login': typeof NoauthLoginRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/forgot-password' | '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/forgot-password' | '/login' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_noauth'
    | '/_noauth/forgot-password'
    | '/_noauth/login'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  NoauthRouteRoute: typeof NoauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_noauth': {
      id: '/_noauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_noauth/login': {
      id: '/_noauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof NoauthLoginRouteImport
      parentRoute: typeof NoauthRouteRoute
    }
    '/_noauth/forgot-password': {
      id: '/_noauth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof NoauthForgotPasswordRouteImport
      parentRoute: typeof NoauthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface NoauthRouteRouteChildren {
  NoauthForgotPasswordRoute: typeof NoauthForgotPasswordRoute
  NoauthLoginRoute: typeof NoauthLoginRoute
}

const NoauthRouteRouteChildren: NoauthRouteRouteChildren = {
  NoauthForgotPasswordRoute: NoauthForgotPasswordRoute,
  NoauthLoginRoute: NoauthLoginRoute,
}

const NoauthRouteRouteWithChildren = NoauthRouteRoute._addFileChildren(
  NoauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  NoauthRouteRoute: NoauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
