# ---------- Base Builder ----------
FROM node:22-alpine AS upstream

FROM upstream AS base

WORKDIR /app
COPY ./app/ ./

# ---------- Development Stage ----------
FROM base AS development

ENV NODE_ENV=development

# Install dependencies
RUN npm i

CMD [ "npm", "run", "dev" ]

# ---------- Production Build ----------
FROM base AS build
RUN npm run build

WORKDIR /app/build

RUN npm ci --omit="dev"

# ---------- Production Runtime ----------
FROM upstream AS production

WORKDIR /app

ENV NODE_ENV=production

# Only copy production output
COPY --from=build /app/dist/ .

CMD [ "npx", "serve", "." ]
