# ---------- Base Builder ----------
FROM node:22-alpine AS base

WORKDIR /app
COPY ./server/ ./

# ---------- Development Stage ----------
FROM base AS development

# Install dependencies
RUN npm ci
CMD ["npm", "run", "dev"]

# ---------- Production Build ----------
FROM base AS build
RUN npm run build

WORKDIR /app/build

COPY /app/.env* .
RUN npm ci --omit="dev"

# ---------- Production Runtime ----------
FROM node:22-alpine AS production

WORKDIR /app

# Only copy production output
COPY --from=build /app/build/ .

CMD ["node", "bin/server.js"]
