# ---------- Base Builder ----------
FROM node:22-alpine AS upstream

RUN npm install -g @infisical/cli

COPY ./entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint
ENTRYPOINT [ "/usr/local/bin/docker-entrypoint" ]

FROM upstream AS base

WORKDIR /app
COPY ./server/ ./

# ---------- Development Stage ----------
FROM base AS development

ENV NODE_ENV=development

# Install watchexec
RUN apk add --no-cache watchexec

# Install dependencies
RUN npm ci

# ---------- Production Runtime ----------
FROM base AS production

ENV NODE_ENV=production

RUN npm ci --omit="dev"
