FROM caddy:2-builder-alpine AS builder

RUN xcaddy build

# Optional: Add plugins here
# RUN xcaddy build \
#     --with github.com/caddy-dns/cloudflare \
#     --with github.com/mholt/caddy-l4

### DEVELOPMENT STAGE. WATCHES CADDYFILE FOR CHANGES
FROM caddy:2-alpine AS development

# Copy the custom-built binary & default entrypoint
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY ./files/Caddyfile /etc/caddy/Caddyfile

# Launch Caddy with file‐watching (for dev)

# Install watchexec
RUN apk add --no-cache watchexec
CMD ["watchexec", "-r", "-w", "/etc/caddy/Caddyfile", "--poll=5s", "caddy", "run", "--config", "/etc/caddy/Caddyfile"]

### PRODUCTION STAGE
FROM caddy:2-alpine AS production

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
COPY ./files/Caddyfile /etc/caddy/Caddyfile

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile"]
